### ISSUE TITLE
Make apollo.config.js support esm project type:module

### ISSUE THREAD

**Issue by tianyingchun** [apollographql/vscode-graphql#100]
how to make apollo.config.js support esm project type:module

can apollo-tooling support apollo.config.cjs, apollo.config.mjs?

**Comment by alex-tang-carta** [comment]
+1 for this!

**Comment by RajaARK99** [comment]
Any update on this

**Comment by bengry** [comment]
A temporary solution that worked for me was to rename `apollo.config.js` to `apollo.config.ts` and use `export default` in the file. This change seemed to enable the Apollo VS Code extension to load the file correctly. I'm not certain whether it consumes it as ESM or CJS, but it doesn't really matter to me as long as it works. By the way, I have `"type": "module"` in my `package.json`.

**Comment by CowDotDev** [comment]
++ on this still

**Comment by phryneas** [comment]
I just released a 2.0.0 and we now support both an `apollo.config.cjs` and a `apollo.config.mjs`. I hope that resolves this :)
