### ISSUE TITLE
Broken links on VS Marketplace page

### ISSUE THREAD

**Issue by Marcuse7** [apollographql/vscode-graphql#104]
On the [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=mquandalle.graphql) page for this extension the [Issues](https://github.com/apollostack/vscode-graphql/issues) and [Repository](https://github.com/apollostack/vscode-graphql.git) links should be changed to https://github.com/apollographql/vscode-graphql/issues and https://github.com/apollographql/vscode-graphql .

**Comment by alessbell** [comment]
Hi @Marcuse7 👋 It looks like you have the wrong page there: this is the correct one https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo.

When I click the issues and repository links there I'm seeing the correct pages on this repository, so I'm going to go ahead and close this issue out. If I missed anything, do let me know :) Thanks!
