### ISSUE TITLE
No completion when using the #graphql annotation

### ISSUE THREAD

**Issue by arcanis** [apollographql/vscode-graphql#15]
As you can see, strings annotated with #graphql are properly highlighted but the extension doesn't extend them with completion and validation (it only works when using the gql tagged template):

![image](https://user-images.githubusercontent.com/1037931/130152714-b6434874-2a8f-497d-83b4-bd2acdb6b535.png)

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-356) by [Unito](https://www.unito.io)

**Comment by jgzuke** [comment]
This should be fixed in the latest release! Thanks for reporting 🎉
