### ISSUE TITLE
Stop auto switch/focus on error

### ISSUE THREAD

**Issue by airtonix** [apollographql/vscode-graphql#16]
It's pretty annoying that this plugin switches to the output tab and focuses it whenever there's an error/warning it wants to let you know about.

Is there a setting we can toggle to disable this behaviour?

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-365) by [Unito](https://www.unito.io)

**Comment by ingdanko** [comment]
Please either disable this behaviour altogether, or let us disable it by adding an option to the extension settings. Every time I checkout a branch, the output tab pops up. This makes the extension borderline unusable.

**Comment by jgzuke** [comment]
@DanielBreiner implemented this over in https://github.com/apollographql/vscode-graphql/pull/44, will be out soon!

**Comment by jgzuke** [comment]
Just released the setting, you can find it in VSCode settings under 'Apollo GraphQL' 😄 

Thank you for reporting 🎉
