### ISSUE TITLE
Loading current apollo.config.ts file broke in V2

### ISSUE THREAD

**Issue by yoavbls** [apollographql/vscode-graphql#170]
This is our config file (`apollo.config.ts`) which we haven't changed in a while:

```ts
module.exports = {
  client: {
    service: {
      name: 'the-graph',
      localSchemaFile: 'schema.generated.graphql',
    },
    includes: ['src/**/*'],
    excludes: ['src/@generated/**/*'],
  },
};

```

After upgrading the extension to V2 it broke and showed this error toast non-stop:
<img src="https://github.com/user-attachments/assets/14ab5e87-541c-4d40-8962-9b55cd1d836c" width="500">
  
  
And this error was repeated countless times in the Output panel:
```
---
Error: A config file failed to load with options: {"configPath":"/Users/..."}.
    The error was: ReferenceError: module is not defined in ES module scope
    at loadConfig (/Users/.../.vscode/extensions/apollographql.vscode-apollo-2.0.0/lib/language-server/server.js:790:1869)
    at async Promise.all (index 0)
    at async J1e.addProjectsInFolder (/Users/.../.vscode/extensions/apollographql.vscode-apollo-2.0.0/lib/language-server/server.js:1036:3098)
    at async Promise.all (index 0)
    at async /Users/.../.vscode/extensions/apollographql.vscode-apollo-2.0.0/lib/language-server/server.js:1061:5425
---
```
  
  

I guess it is related to [this](https://github.com/apollographql/vscode-graphql/issues/100#issuecomment-2284185774).  
We're glad that ESModules is supported now but it's breaking (at least in `.ts` files)

Thank you 🙂

**Comment by phryneas** [comment]
Hi Yoav!

I believe with the updated `cosmiconfig`, it now detects that your project is using ESM, so TypeScript expects you to use `export` instead of `module.exports`.

Could you try to change your configuration to 

```ts
export default {
  client: {
    service: {
      name: 'the-graph',
      localSchemaFile: 'schema.generated.graphql',
    },
    includes: ['src/**/*'],
    excludes: ['src/@generated/**/*'],
  },
};
```
and report back if that works?

**Comment by phryneas** [comment]
That said, this is really an unexpected change and we should support both. 
I've opened #171 with a fix, and I expect to ship this later today, after it got reviewed :)

**Comment by yoavbls** [comment]
Thank you @phryneas! 
Yes it is working, I just wanted to make sure it is not breaking for others 🙏🏼

**Comment by phryneas** [comment]
The fix is rolling out now :)
