### ISSUE TITLE
Falsy "️️There are multiple definitions for the operation" triggered

### ISSUE THREAD

**Issue by yhaskell** [apollographql/vscode-graphql#18]
I see a lot of failures in the Apollo GraphQL Output for vscode, that looks like this:

    [Error - 18:28:53] Notification handler 'workspace/didChangeWatchedFiles' failed with message: ️️There are multiple definitions for the `OperationName` operation. Please rename or remove all operations with the duplicated name before continuing.When I search for this operation, I don't find it anymore. 
Restarting vscode helps, but not for a long time.

Can we please have in this error actual places where it finds the problems?
That would help to understand the issue more, and actually help immensely when this problem actually occur.

Thank you!

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-433) by [Unito](https://www.unito.io)

**Comment by anders-photowall** [comment]
I have the same or similar issue. The issue for me is that as soon as you open a non-file version of the file containing the definition (i.e. working-tree version or really any diff) the apollo extension reads that and treats it as a duplicate definition. Before finding this issue I found this pull request on the old extension repo which actually fixes the issue but it was never merged: 
https://github.com/apollographql/apollo-tooling/pull/1894

**Comment by jgzuke** [comment]
This is my next priority to get fixed! Hoping to get to it soon but unfortunately haven't had time

**Comment by memark** [comment]
Thank you @jgzuke, looking forward to it!

**Comment by jgzuke** [comment]
This should be fixed in the latest `1.19.7` release 😄
