### ISSUE TITLE
`importAttributes` not available in old node versions

### ISSUE THREAD

**Issue by phryneas** [apollographql/vscode-graphql#225]
reported by @weiatresvu here https://github.com/apollographql/vscode-graphql/pull/204#pullrequestreview-2361756806

> It was ⁠context.importAssertions. So, in some older versions of Node.js, context importAttributes will be undefined. Unfortunately, Cursor is using Node.js 20.9.0 in their latest version.
> 
> See, [nodejs.org/api/module.html#hooks:~:text=v21.0.0%2C v20.10.0%2C v18.19.0](https://nodejs.org/api/module.html#hooks:~:text=v21.0.0%2C%20v20.10.0%2C%20v18.19.0)

This would also impact VSCode before 1.92 (see [chart](https://github.com/ewanharris/vscode-versions), our current minimum is 1.90) so we will need a workaround for that.

@weiatresvu would you be open for a PR on this? :)

**Comment by weiatresvu** [comment]
Happy to propose a PR.
