### ISSUE TITLE
Support Deprecated Input

### ISSUE THREAD

**Issue by eMerzh** [apollographql/vscode-graphql#30]
Hello :wave: , 
thanks for your work :) 

my vscode is yelling at me because i got some fields that are input and deprecated....
although it's supported in graphql-js now (https://github.com/graphql/graphql-js/pull/2855) 

i wonder if there's a way to support that :) 

Regards

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-509) by [Unito](https://www.unito.io)

**Comment by jgzuke** [comment]
Thanks for raising 😄 This upgrade will take a bit of work, hopefully will have it sorted out tomorrow!

**Comment by jgzuke** [comment]
Hey! This should be fixed in the latest `1.19.7` release 😄
