### ISSUE TITLE
Parser doesn't understand modern graphql syntax

### ISSUE THREAD

**Issue by krainboltgreene** [apollographql/vscode-graphql#33]
![](https://user-images.githubusercontent.com/334809/136712782-2424c225-a96f-494f-a331-251d67916d0c.png)

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-510) by [Unito](https://www.unito.io)

**Comment by jgzuke** [comment]
Hey! I think this should be fixed in the latest release. I cant quite tell by the screenshots but if the description here is accurate this should no longer be an issue.

Gonna close for now, but feel free to reopen if you're still getting this
