### ISSUE TITLE
Is there a way to disable the "run in studio" button through some vscode setting?

### ISSUE THREAD

**Issue by benatshippabo** [apollographql/vscode-graphql#37]
Is there a way to disable the "run in studio" button through a vscode setting? I find the increased indentation disorienting.

![image](https://user-images.githubusercontent.com/66273043/138192832-ad07bdca-b6f9-4957-afc5-ea25d2638f3f.png)

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-551) by [Unito](https://www.unito.io)

**Comment by ivnnv** [comment]
+100
To this should be an opt-in (off by default) option because having a config file doesn't necessarily means we have access or want to use studio.

**Comment by talon-i-am** [comment]
+1

**Comment by whengely** [comment]
Please add a way to disable this.  Not only does it clutter my screen, it also pushes text further to the right so it doesn't line up.

**Comment by jgzuke** [comment]
Hey y'all, Sorry for the wait! We ended up moving the button to the end of the line after the text over in https://github.com/apollographql/vscode-graphql/pull/42, we're hoping that this solves:
- Increased indentation / pushing the text to the right
- Extra clutter of the screen
- Allows people who don't want to use Sandbox to ignore the button

I'm hesitant to add a config given that the Apollo config in it's current state is honestly pretty confusing (which I hope we can fix!). I'm hoping that this being moved out of the way will alleviate the need for people to turn it off, while still allowing those that have started using it to continue, and not needing to add any complexity to the config.

Thank you for raising this issue! Honestly it fell off my radar for a while, sorry it took so long to get to 🙏

Going to close for now, if this is still an issue after this change let us know!

**Comment by yusufumac** [comment]
Jason, it is a clutter if some people don't use it and is not easy to ignore a big blue button on every query. As far as I know, Apollo VS code extension doesn't have many configs. Adding a config option to hide these button while keeping the default as shown won't affect the current users but it gives the ability to hide it for people who is never going to use it.

**Comment by ivnnv** [comment]
Man... this is such a cheap solution... 😄 

![button](https://user-images.githubusercontent.com/23552631/141266170-65e1f5e1-7dcd-446c-af38-f37d5503a313.png)

**Comment by benatshippabo** [comment]
@jgzuke,  @yusufumac is right, there is currently only one other vscode configuration setting:

https://github.com/apollographql/vscode-graphql/blob/89d014a1069845b203ad36a2962b2b94822f8292/package.json#L104-L120

I think we can follow [one of the pending PRs as an example](https://github.com/apollographql/vscode-graphql/pull/44) and then check for the configuration value in the if statement here:

https://github.com/apollographql/vscode-graphql/blob/89d014a1069845b203ad36a2962b2b94822f8292/src/extension.ts#L248

**Comment by jgzuke** [comment]
Ah gotcha, that makes more sense, I thought you meant an option in the Apollo config! Im still learning the extension contribution points, happy to have that option brought up 😄 Will add an option as I do think it makes sense there

Opened at https://github.com/apollographql/vscode-graphql/pull/46

**Comment by jgzuke** [comment]
Setting released! `Show a "Run in Studio" button to the right of Operation Signatures.` under `Apollo GraphQL`

**Comment by benatshippabo** [comment]
> Setting released! `Show a "Run in Studio" button to the right of Operation Signatures.` under `Apollo GraphQL`

Noiceeee! 🎉

**Comment by ivnnv** [comment]
Finally!
Thanks @jgzuke for the PR and the apollo team for listening to the community and merging it so quick :)
