### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DoDangDucCoder** [apollographql/vscode-graphql#39]
* Issue Type: `Performance`
* Extension Name: `vscode-apollo`
* Extension Version: `1.19.7`
* OS Version: `Windows_NT x64 10.0.19043`
* VS Code version: `1.61.2`

:warning: Make sure to **attach** this file from your _home_-directory:
:warning:`c:\Users\Admin\AppData\Local\Temp\apollographql.vscode-apollo-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-569) by [Unito](https://www.unito.io)

**Comment by jgzuke** [comment]
@do-dnang-duc this is missing the profile file
