### ISSUE TITLE
Add setting for ignoring/excluding a file pattern from 

### ISSUE THREAD

**Issue by Stormix** [apollographql/vscode-graphql#56]
# Problem:
[graphql-code-generator](https://graphql-code-generator.com/) is a widely used tooling that provides types generation from`.graphql`/`.gql` schema files, it can also automatically generate hooks to be used in a React + Typescript environment.

Graphql Queries/Mutations/Subscriptions can be defined inside a folde that the code generator then uses to build custom React hooks that wrap the query in a gql literal string tag.

For example:

Given this query:

```graphql
query GetCurrentUser {
  currentUser {
    id
  }
}
```

You get the following output:

```typescript
export const GetCurrentUserDocument = gql`
  query GetCurrentUser {
    currentUser {
      id
    }
  }
`;
```

The issue starts when Apollo Plugin attempts to parse this generated query. Since the project already has another query with the same name, as it was copied directly from the original definition, The Apollo Plugin crashes due to duplicated query names.

# Proposed solution:
Add the option to ignore files matching a certain pattern (Eg: ` src/__auto_generated__/**`, `src/hooks/GeneratedHooks/**`).

- - -
This issue has been reported before and can be found here on the old repo:  https://github.com/apollographql/apollo-tooling/issues/2064 

Could be related to: https://github.com/apollographql/vscode-graphql/issues/40

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-793) by [Unito](https://www.unito.io)

**Comment by mbrandau** [comment]
There actually is an option to that. https://www.apollographql.com/docs/devtools/apollo-config/#clientexcludes
I had the same problem and this seemed to do the trick for me.
I have all operations in one folder and am now only including that while also excluding the generated code.
