### ISSUE TITLE
Issues with GraphQL heredoc in ruby files

### ISSUE THREAD

**Issue by marin-takanov** [apollographql/vscode-graphql#74]
Hello,

While working on Ruby on Rails project, I noticed that the highlighting in the spec files is somehow wrong when using heredocs for GraphQL. It seems that after the first GraphQL heredoc, everything goes in yellow, the formatting while writing and the autocomplete doesn't work. I'm attaching a screenshot.

Example:

```
# foo_spec.rb

require 'rails_helper'

module Graph
  module Mutations
    describe FooMutation do
      it 'flags foo' do
        foo = create :foo

        resolve <<~GRAPHQL, id: foo.id, flag: true
          mutation($id: ID!, $flag: Boolean!) {
            flagFoo(input: {id: $id, flag: $flag}) {
              foo {
                flagged
              }
            }
          }
        GRAPHQL

        response_data.should eq 'flagFoo' => {'foo' => {'flagged' => true}]}
      end

      it 'unflags foo' do
        foo = create :foo

        resolve <<~GRAPHQL, id: foo.id, flag: false
          mutation($id: ID!, $flag: Boolean!) {
            flagFoo(input: {id: $id, flag: $flag}) {
              foo {
                flagged
              }
            }
          }
        GRAPHQL

        response_data.should eq 'flagFoo' => {'foo' => {'flagged' => false}}
      end
    end
  end
end


```

</details>

<details>
<summary>Screenshot</summary>

![Screenshot 2022-05-25 at 14 56 53](https://user-images.githubusercontent.com/61980712/170256610-4443e12c-d757-434e-a721-d45d42d99775.png)

</details>

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1307) by [Unito](https://www.unito.io)

**Comment by jtgrenz** [comment]
I'm also running into this issue. If I change the heredoc to something other than `<<-GRAPHQL` or `<<~GRAPHQL`, I loose the graphql highlighting but the rest of the file works as normal. I think that means its something to do with the regex here https://github.com/apollographql/vscode-graphql/blob/main/syntaxes/graphql.rb.json 

![image](https://user-images.githubusercontent.com/2111778/178365645-c5efd85e-f5cb-4dec-a978-bd4cf708d8ea.png)

![image](https://user-images.githubusercontent.com/2111778/178365717-15086cc7-f000-489c-ae59-7b104e0a5e79.png)
