### ISSUE TITLE
don't work vite version 3 

### ISSUE THREAD

**Issue by hmz22** [apollographql/vscode-graphql#79]
in vite version 3 package.json type:"module" and when i create apollo.config.js and add module.export  = {...} dont complie and show error change type to commonjs or cjs and I change file name to apollo.config.cjs don't work and when change type to commonjs, vite don't work please fix this problem

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1488) by [Unito](https://www.unito.io)

**Comment by danielb7390** [comment]
Having the same problem. When i rename the file to `apollo.config.cjs` i get this error:

> It looks like there are 0 files associated with this Apollo Project. This may be because you don't have any files yet, or your includes/excludes fields are configured incorrectly, and Apollo can't find your files. For help configuring Apollo projects, see this guide: https://go.apollo.dev/t/config

If i rename the file back to `apollo.config.js` and set `"type": "commonjs"`, the plugin works fine. But now my project is broken 😅

**Comment by Foresteam** [comment]
Same issue.
https://github.com/apollographql/apollo-tooling/issues/2683

**Comment by iamolegga** [comment]
Any progress on this?

**Comment by alessbell** [comment]
Could you try again with v1.20.0 (just released to the VS Code marketplace) @danielb7390? Or if anyone else is able to try that out. It should now detect config files with the `.cjs` extension, thanks!

**Comment by PuffCab** [comment]
> Could you try again with v1.20.0 (just released to the VS Code marketplace) @danielb7390? Or if anyone else is able to try that out. It should now detect config files with the `.cjs` extension, thanks!

It works now , with v1.20.0 and  `.cjs` extension for th config file .

![Screenshot 2024-01-17 at 19 21 47](https://github.com/apollographql/vscode-graphql/assets/87316687/ddd5d31b-4c77-4396-b10b-5e96c47e925c)

Thanks a lot!

**Comment by alessbell** [comment]
Thanks for confirming @PuffCab! I'll go ahead and close out this issue.
