### ISSUE TITLE
Comment toggling doesn't work in tagged templates

### ISSUE THREAD

**Issue by runofthemill** [apollographql/vscode-graphql#82]
While in one of the Summit Day 0 workshops (the PM Federation Workshop - ask Mike if he can answer a question about recursion :wink:) I noticed <kbd>command</kbd>+<kbd>/</kbd> wasn't toggling the comments in a [`gql` tagged template](https://github.com/apollosolutions/federation-workshop/blob/main/client/src/pages/Homepage.jsx#L17-L41).

FWIW, I tried with the [GraphQL: Language Feature Support
](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) extension and it works as expected; I cloned this repo to "develop" the extension locally, and copying the configuration from [`graphql.js.json`](https://github.com/graphql/graphiql/blob/main/packages/vscode-graphql-syntax/grammars/graphql.js.json) to this extension's corresponding `graphql.js.json` makes it work, but there are a bunch of differences between the configs so I don't know which part addresses the issue ¯\_(ツ)_/¯ Happy to open a PR anyways, if that's helpful!

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1791) by [Unito](https://www.unito.io)

**Comment by duckki** [comment]
+1
The toggle comment doesn't seem to work in plain .graphql files, either.

**Comment by phryneas** [comment]
Hi there, I'm sorry for the late response!

We recently reworked the detection of code blocks, so this should work now. 

If it still doesn't, please open a new issue with example code where it doesn't work, and I'll happily take a look :)

**Comment by phryneas** [comment]
Actually I just found out that due to a build error, this worked only locally for us extension developers, but not for our users 🤦 

I'm sorry, I'll release a fix within the next few minutes.
