### ISSUE TITLE
VSCode: Plugin doesn't work in multi-root workspaces

### ISSUE THREAD

**Issue by intellix** [apollographql/vscode-graphql#85]
Previous: https://github.com/apollographql/apollo-tooling/issues/821

If you're using a tool such as nrwl/nx where you have entry points in the "app" folder and libraries in a "libs" folder, it's not possible to configure this plugin to search in anywhere other than the "src" folder.

┆Issue is synchronized with this [Jira Task](https://apollographql.atlassian.net/browse/NEBULA-1890) by [Unito](https://www.unito.io)

**Comment by natterstefan** [comment]
Hello all,

is there any news on how to support repos with lerna (`packages/*`) in interaction with multi-root workspaces (e.g. `backend` and `client` managed in different repos but opened in a multi-root workspace at the same time)?

Thank you for your feedback.

**Comment by intellix** [comment]
Just looking at the code and the documentation I'm wondering if this is configurable now (not sure when it became so):

From the docs https://www.apollographql.com/docs/devtools/editor-plugins/#client-only-schemas:
> By default, the VS Code extension will look for all files under ./src to find both the operations and schema definitions for building a complete schema for the application.

The code shows a ./src being the default, but I assume you can extend it: https://github.com/apollographql/vscode-graphql/blob/f9fad260dbda61a6870f3b23cc7621d83ce06da2/src/language-server/config/config.ts#L44

Yep, I can confirm that it now works for me:

Example:
```
module.exports = {
  client: {
    service: 'my-service@production',
    includes: ['{apps,libs}/**/*.{ts,tsx,js,jsx,graphql,gql}']
  },
};
```

**Comment by natterstefan** [comment]
Hey @intellix,

thanks for the update. But one can't add multiple `apollo.config.js` files into different projects in the same workspace, or where did you put this file?

Example:

```
repo-1/apollo.config.js
repo-2/apollo.config.js
```

And both are opened as one workspace in VS Code.
