### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mishi20** [apollographql/vscode-graphql#9]
- Issue Type: `Performance`
- Extension Name: `vscode-apollo`
- Extension Version: `1.19.4`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Mariela\AppData\Local\Temp\apollographql.vscode-apollo-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jgzuke** [comment]
@Mishi20 I think you may have meant to attach the profile here 😄

**Comment by jgzuke** [comment]
Not much we can do here, gonna close this for now
