### ISSUE TITLE
tag with parens doesnt work

### ISSUE THREAD

**Issue by pvinis** [apollographql/vscode-graphql#98]
when i have
```
const myQuery = gql`
  query Wow {
    whatever {
      id
    }
  }
```
then autocomplete works, and syntax highlight works, so i could go under `id` and type `la` and id get a `label` suggestion.

but with
```
const myQuery = gql(`
  query Wow {
    whatever {
      id
    }
  }
`)
```
which unfortunately is required for typescript and codegen to work, now autocomplete and syntax highlight doesnt work!

can you fix is so that with parens, both autocomplete and syntax highlight works?

**Comment by avele** [comment]
I am facing the same issue. It would be helpful if we could at least pass a raw regular expression, which is what the original tagName is eventually translated into anyway.
